//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web.AdAuthentication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAuthenticationGetUserRoles", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    [System.SerializableAttribute()]
    public partial class UserAuthenticationGetUserRoles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        private int RoleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleListField;
        
        private bool HasRolesField;
        
        private bool IsAuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private bool HasExceptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CommonName {
            get {
                return this.CommonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommonNameField, value) != true)) {
                    this.CommonNameField = value;
                    this.RaisePropertyChanged("CommonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoleCount {
            get {
                return this.RoleCountField;
            }
            set {
                if ((this.RoleCountField.Equals(value) != true)) {
                    this.RoleCountField = value;
                    this.RaisePropertyChanged("RoleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleList {
            get {
                return this.RoleListField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleListField, value) != true)) {
                    this.RoleListField = value;
                    this.RaisePropertyChanged("RoleList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool HasRoles {
            get {
                return this.HasRolesField;
            }
            set {
                if ((this.HasRolesField.Equals(value) != true)) {
                    this.HasRolesField = value;
                    this.RaisePropertyChanged("HasRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsAuthenticated {
            get {
                return this.IsAuthenticatedField;
            }
            set {
                if ((this.IsAuthenticatedField.Equals(value) != true)) {
                    this.IsAuthenticatedField = value;
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool HasExceptions {
            get {
                return this.HasExceptionsField;
            }
            set {
                if ((this.HasExceptionsField.Equals(value) != true)) {
                    this.HasExceptionsField = value;
                    this.RaisePropertyChanged("HasExceptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAuthentication", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    [System.SerializableAttribute()]
    public partial class UserAuthentication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        private bool IsAuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        private bool HasExceptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CommonName {
            get {
                return this.CommonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommonNameField, value) != true)) {
                    this.CommonNameField = value;
                    this.RaisePropertyChanged("CommonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsAuthenticated {
            get {
                return this.IsAuthenticatedField;
            }
            set {
                if ((this.IsAuthenticatedField.Equals(value) != true)) {
                    this.IsAuthenticatedField = value;
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool HasExceptions {
            get {
                return this.HasExceptionsField;
            }
            set {
                if ((this.HasExceptionsField.Equals(value) != true)) {
                    this.HasExceptionsField = value;
                    this.RaisePropertyChanged("HasExceptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserRoles", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    [System.SerializableAttribute()]
    public partial class GetUserRoles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        private int RoleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleListField;
        
        private bool HasRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        private bool HasExceptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoleCount {
            get {
                return this.RoleCountField;
            }
            set {
                if ((this.RoleCountField.Equals(value) != true)) {
                    this.RoleCountField = value;
                    this.RaisePropertyChanged("RoleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleList {
            get {
                return this.RoleListField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleListField, value) != true)) {
                    this.RoleListField = value;
                    this.RaisePropertyChanged("RoleList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool HasRoles {
            get {
                return this.HasRolesField;
            }
            set {
                if ((this.HasRolesField.Equals(value) != true)) {
                    this.HasRolesField = value;
                    this.RaisePropertyChanged("HasRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CommonName {
            get {
                return this.CommonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommonNameField, value) != true)) {
                    this.CommonNameField = value;
                    this.RaisePropertyChanged("CommonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool HasExceptions {
            get {
                return this.HasExceptionsField;
            }
            set {
                if ((this.HasExceptionsField.Equals(value) != true)) {
                    this.HasExceptionsField = value;
                    this.RaisePropertyChanged("HasExceptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", ConfigurationName="AdAuthentication.ADAuthenticationInternalSoap")]
    public interface ADAuthenticationInternalSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ADAuthenticationInternal/ADAuthentication is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADAuthenticationInternal/ADAuthentication/SubmitUserAuthentica" +
            "tionGetUserRoles", ReplyAction="*")]
        Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponse SubmitUserAuthenticationGetUserRoles(Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADAuthenticationInternal/ADAuthentication/SubmitUserAuthentica" +
            "tionGetUserRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponse> SubmitUserAuthenticationGetUserRolesAsync(Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ADAuthenticationInternal/ADAuthentication is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADAuthenticationInternal/ADAuthentication/SubmitUserAuthentica" +
            "tion", ReplyAction="*")]
        Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponse SubmitUserAuthentication(Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADAuthenticationInternal/ADAuthentication/SubmitUserAuthentica" +
            "tion", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponse> SubmitUserAuthenticationAsync(Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ADAuthenticationInternal/ADAuthentication is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADAuthenticationInternal/ADAuthentication/SubmitGetUserRoles", ReplyAction="*")]
        Inventory.Web.AdAuthentication.SubmitGetUserRolesResponse SubmitGetUserRoles(Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADAuthenticationInternal/ADAuthentication/SubmitGetUserRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitGetUserRolesResponse> SubmitGetUserRolesAsync(Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitUserAuthenticationGetUserRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitUserAuthenticationGetUserRoles", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", Order=0)]
        public Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequestBody Body;
        
        public SubmitUserAuthenticationGetUserRolesRequest() {
        }
        
        public SubmitUserAuthenticationGetUserRolesRequest(Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    public partial class SubmitUserAuthenticationGetUserRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApplicationName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IPAddress;
        
        public SubmitUserAuthenticationGetUserRolesRequestBody() {
        }
        
        public SubmitUserAuthenticationGetUserRolesRequestBody(string UserName, string Password, string ApplicationName, string IPAddress) {
            this.UserName = UserName;
            this.Password = Password;
            this.ApplicationName = ApplicationName;
            this.IPAddress = IPAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitUserAuthenticationGetUserRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitUserAuthenticationGetUserRolesResponse", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", Order=0)]
        public Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponseBody Body;
        
        public SubmitUserAuthenticationGetUserRolesResponse() {
        }
        
        public SubmitUserAuthenticationGetUserRolesResponse(Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    public partial class SubmitUserAuthenticationGetUserRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Inventory.Web.AdAuthentication.UserAuthenticationGetUserRoles SubmitUserAuthenticationGetUserRolesResult;
        
        public SubmitUserAuthenticationGetUserRolesResponseBody() {
        }
        
        public SubmitUserAuthenticationGetUserRolesResponseBody(Inventory.Web.AdAuthentication.UserAuthenticationGetUserRoles SubmitUserAuthenticationGetUserRolesResult) {
            this.SubmitUserAuthenticationGetUserRolesResult = SubmitUserAuthenticationGetUserRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitUserAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitUserAuthentication", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", Order=0)]
        public Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequestBody Body;
        
        public SubmitUserAuthenticationRequest() {
        }
        
        public SubmitUserAuthenticationRequest(Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    public partial class SubmitUserAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApplicationName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IPAddress;
        
        public SubmitUserAuthenticationRequestBody() {
        }
        
        public SubmitUserAuthenticationRequestBody(string UserName, string Password, string ApplicationName, string IPAddress) {
            this.UserName = UserName;
            this.Password = Password;
            this.ApplicationName = ApplicationName;
            this.IPAddress = IPAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitUserAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitUserAuthenticationResponse", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", Order=0)]
        public Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponseBody Body;
        
        public SubmitUserAuthenticationResponse() {
        }
        
        public SubmitUserAuthenticationResponse(Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    public partial class SubmitUserAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Inventory.Web.AdAuthentication.UserAuthentication SubmitUserAuthenticationResult;
        
        public SubmitUserAuthenticationResponseBody() {
        }
        
        public SubmitUserAuthenticationResponseBody(Inventory.Web.AdAuthentication.UserAuthentication SubmitUserAuthenticationResult) {
            this.SubmitUserAuthenticationResult = SubmitUserAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitGetUserRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitGetUserRoles", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", Order=0)]
        public Inventory.Web.AdAuthentication.SubmitGetUserRolesRequestBody Body;
        
        public SubmitGetUserRolesRequest() {
        }
        
        public SubmitGetUserRolesRequest(Inventory.Web.AdAuthentication.SubmitGetUserRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    public partial class SubmitGetUserRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApplicationName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IPAddress;
        
        public SubmitGetUserRolesRequestBody() {
        }
        
        public SubmitGetUserRolesRequestBody(string UserName, string ApplicationName, string IPAddress) {
            this.UserName = UserName;
            this.ApplicationName = ApplicationName;
            this.IPAddress = IPAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitGetUserRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitGetUserRolesResponse", Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication", Order=0)]
        public Inventory.Web.AdAuthentication.SubmitGetUserRolesResponseBody Body;
        
        public SubmitGetUserRolesResponse() {
        }
        
        public SubmitGetUserRolesResponse(Inventory.Web.AdAuthentication.SubmitGetUserRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ADAuthenticationInternal/ADAuthentication")]
    public partial class SubmitGetUserRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Inventory.Web.AdAuthentication.GetUserRoles SubmitGetUserRolesResult;
        
        public SubmitGetUserRolesResponseBody() {
        }
        
        public SubmitGetUserRolesResponseBody(Inventory.Web.AdAuthentication.GetUserRoles SubmitGetUserRolesResult) {
            this.SubmitGetUserRolesResult = SubmitGetUserRolesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ADAuthenticationInternalSoapChannel : Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADAuthenticationInternalSoapClient : System.ServiceModel.ClientBase<Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap>, Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap {
        
        public ADAuthenticationInternalSoapClient() {
        }
        
        public ADAuthenticationInternalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADAuthenticationInternalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADAuthenticationInternalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADAuthenticationInternalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponse Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap.SubmitUserAuthenticationGetUserRoles(Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest request) {
            return base.Channel.SubmitUserAuthenticationGetUserRoles(request);
        }
        
        public Inventory.Web.AdAuthentication.UserAuthenticationGetUserRoles SubmitUserAuthenticationGetUserRoles(string UserName, string Password, string ApplicationName, string IPAddress) {
            Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest inValue = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest();
            inValue.Body = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.ApplicationName = ApplicationName;
            inValue.Body.IPAddress = IPAddress;
            Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponse retVal = ((Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap)(this)).SubmitUserAuthenticationGetUserRoles(inValue);
            return retVal.Body.SubmitUserAuthenticationGetUserRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponse> Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap.SubmitUserAuthenticationGetUserRolesAsync(Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest request) {
            return base.Channel.SubmitUserAuthenticationGetUserRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesResponse> SubmitUserAuthenticationGetUserRolesAsync(string UserName, string Password, string ApplicationName, string IPAddress) {
            Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest inValue = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequest();
            inValue.Body = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationGetUserRolesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.ApplicationName = ApplicationName;
            inValue.Body.IPAddress = IPAddress;
            return ((Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap)(this)).SubmitUserAuthenticationGetUserRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponse Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap.SubmitUserAuthentication(Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest request) {
            return base.Channel.SubmitUserAuthentication(request);
        }
        
        public Inventory.Web.AdAuthentication.UserAuthentication SubmitUserAuthentication(string UserName, string Password, string ApplicationName, string IPAddress) {
            Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest inValue = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest();
            inValue.Body = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.ApplicationName = ApplicationName;
            inValue.Body.IPAddress = IPAddress;
            Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponse retVal = ((Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap)(this)).SubmitUserAuthentication(inValue);
            return retVal.Body.SubmitUserAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponse> Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap.SubmitUserAuthenticationAsync(Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest request) {
            return base.Channel.SubmitUserAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitUserAuthenticationResponse> SubmitUserAuthenticationAsync(string UserName, string Password, string ApplicationName, string IPAddress) {
            Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest inValue = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequest();
            inValue.Body = new Inventory.Web.AdAuthentication.SubmitUserAuthenticationRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.ApplicationName = ApplicationName;
            inValue.Body.IPAddress = IPAddress;
            return ((Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap)(this)).SubmitUserAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventory.Web.AdAuthentication.SubmitGetUserRolesResponse Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap.SubmitGetUserRoles(Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest request) {
            return base.Channel.SubmitGetUserRoles(request);
        }
        
        public Inventory.Web.AdAuthentication.GetUserRoles SubmitGetUserRoles(string UserName, string ApplicationName, string IPAddress) {
            Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest inValue = new Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest();
            inValue.Body = new Inventory.Web.AdAuthentication.SubmitGetUserRolesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.ApplicationName = ApplicationName;
            inValue.Body.IPAddress = IPAddress;
            Inventory.Web.AdAuthentication.SubmitGetUserRolesResponse retVal = ((Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap)(this)).SubmitGetUserRoles(inValue);
            return retVal.Body.SubmitGetUserRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitGetUserRolesResponse> Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap.SubmitGetUserRolesAsync(Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest request) {
            return base.Channel.SubmitGetUserRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Inventory.Web.AdAuthentication.SubmitGetUserRolesResponse> SubmitGetUserRolesAsync(string UserName, string ApplicationName, string IPAddress) {
            Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest inValue = new Inventory.Web.AdAuthentication.SubmitGetUserRolesRequest();
            inValue.Body = new Inventory.Web.AdAuthentication.SubmitGetUserRolesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.ApplicationName = ApplicationName;
            inValue.Body.IPAddress = IPAddress;
            return ((Inventory.Web.AdAuthentication.ADAuthenticationInternalSoap)(this)).SubmitGetUserRolesAsync(inValue);
        }
    }
}
